"""Add Unit.ratio_gr

Revision ID: abaa0bc80300
Revises: cde285d77e24
Create Date: 2024-06-09 21:46:28.786693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abaa0bc80300'
down_revision: Union[str, None] = 'cde285d77e24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit', sa.Column('ratio_gr', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unit', 'ratio_gr')
    # ### end Alembic commands ###
