import os

SECRET_TOKEN_RESET_PASSWORD = os.getenv("SECRET_TOKEN_RESET_PASSWORD")
SECRET_TOKEN_VERIFICATION = os.getenv("SECRET_TOKEN_VERIFICATION")
JWT_SECRET = os.getenv("SECRET_JWT")
DATABASE_URI = os.environ.get("DATABASE_URL")
SQL_REQUESTS_ECHO = bool(int(os.environ.get("SQL_REQUESTS_ECHO", 0)))
APP_NAME = os.environ.get("APP_NAME", "UNKNOWN")
