name: Pylint API

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: Silleellie/pylint-github-action@v2
        with:
          lint-path: src/api
          python-version: ${{ matrix.python-version }}
          badge-text: PyLint API
          requirements-path: requirements-docker.txt